// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azbagas/url-shortening-backend/app"
	"github.com/azbagas/url-shortening-backend/controller"
	"github.com/azbagas/url-shortening-backend/repository"
	"github.com/azbagas/url-shortening-backend/service"
	"github.com/google/wire"
	"net/http"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	userRepository := repository.NewUserRepository()
	refreshTokenRepository := repository.NewRefreshTokenRepository()
	db := app.NewDB()
	validate := app.NewValidator()
	userService := service.NewUserService(userRepository, refreshTokenRepository, db, validate)
	userController := controller.NewUserController(userService)
	router := app.NewRouter(userController)
	server := NewServer(router)
	return server
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, repository.NewRefreshTokenRepository, service.NewUserService, controller.NewUserController)
