// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azbagas/url-shortening-backend/app"
	"github.com/azbagas/url-shortening-backend/middleware"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	viper := app.NewConfig()
	router := app.NewRouter()
	logMiddleware := middleware.NewLogMiddleware(router)
	server := NewServer(viper, logMiddleware)
	return server
}
